# Generated by Django 3.2.3 on 2021-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='domestic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='poisonous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='predator',
            field=models.BooleanField(default=False),
        ),
    ]
