apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-portal-replicaset
spec:
  replicas: 3
  selector:
    app: news-portal
  template:
    metadata:
      name: news-portal
      labels:
        name: news-portal
        app: news-portal
    spec:
      containers:
      - name: news-portal
        image: aluracursos/portal-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: news-portal-configmap
