apiVersion: v1
kind: Pod
metadata:
  name: news-systems
  labels:
    name: news-system
    app: news-system
spec:
  containers:
  - name: news-system
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: news-system-configmap
