apiVersion: v1
kind: Pod
metadata:
  name: declarative-pod
  labels:
    name: declarative-pod
spec:
  containers:
  - name: declarative-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5555
