$mysql_server_installation = <<-SCRIPT
  apt update && \
  apt install -y mysql-server-5.7 && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "private_network", type: "dhcp"
  # config.vm.network "public_network", ip: "192.168.1.66"
  config.vm.synced_folder "./config", "/config"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell",
    inline: "cat /config/id_bionic.pub >> .ssh/authorized_keys"
  config.vm.provision "shell",
    inline: $mysql_server_installation
  config.vm.provision "shell",
    inline: "cat /config/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
  config.vm.provision "shell",
    inline: "service mysql restart"
end
