# Generated by Django 3.2.3 on 2021-05-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pics/%d/%m/%Y/'),
        ),
    ]
