apiVersion: v1
kind: Pod
metadata:
  name: news-db
  labels:
    name: news-db
    app: news-db
spec:
  containers:
  - name: news-db
    image: aluracursos/mysql-db:1
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: news-db-configmap
