apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-systems
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news-system
  template:
    metadata:
      labels:
        app: news-system
    spec:
      containers:
      - name: news-system
        image: aluracursos/sistema-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: news-system-configmap
