apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news-portal
  template:
    metadata:
      labels:
        app: news-portal
    spec:
      containers:
      - name: news-portal
        image: aluracursos/portal-noticias:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: news-portal-configmap
        livenessProbe:
          httpGet:
            port: 80
            path: '/'
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            port: 80
            path: '/'
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3
